name: Documentation Workflow

on:
  push:
    branches:
      - main
      - future
  pull_request:

jobs:
  generateToC:
    name: ToC Generator
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Table of Contents
        uses: technote-space/toc-generator@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
